name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Image tag for rt
      id: meta-rt
      uses: docker/metadata-action@v4
      with:
        images: |
          michaelfung/perl-rt
        tags: |
          type=raw,value=latest
          type=raw,value=5.32.1
          type=sha

    - name: Image tag for devel
      id: meta-devel
      uses: docker/metadata-action@v4
      with:
        images: |
          michaelfung/perl-devel
        tags: |
          type=raw,value=latest
          type=raw,value=5.32.1
          type=sha

    - name: Build and push 'runtime'
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: |
          linux/amd64
          linux/arm/v7
        target: rt
        push: true
        tags: |
          ${{ steps.meta-rt.outputs.tags }}
          ghcr.io/${{ steps.meta-rt.outputs.tags }}

    - name: Build and push 'devel'
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: |
          linux/amd64
          linux/arm/v7
        target: devel
        push: true
        tags: |
          ${{ steps.meta-devel.outputs.tags }}
          ghcr.io/${{ steps.meta-devel.outputs.tags }}
